###############################################################################
# ConfigMap — Keycloak
# KC_DB_URL: ajustar hostname do PostgreSQL após terraform apply
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://psql-heckio-dev.postgres.database.azure.com:5432/keycloak?ssl=true&sslmode=require"
  KC_DB_USERNAME: "pgadmin"
  KEYCLOAK_ADMIN: "admin"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_PROXY: "edge"
  KC_LOG_LEVEL: "INFO"
  KC_HOSTNAME: "traduxai-heck.eastus2.cloudapp.azure.com"
  KC_HOSTNAME_URL: "http://traduxai-heck.eastus2.cloudapp.azure.com"
  KC_HTTP_RELATIVE_PATH: "/auth"
