apiVersion: v1
kind: Service
metadata:
  name: beeai-api
  namespace: beeai-dev
  labels:
    app: beeai-api
spec:
  type: ClusterIP
  selector:
    app: beeai-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
