apiVersion: v1
kind: Service
metadata:
  name: bovipro-api
  namespace: bovipro
  labels:
    app: bovipro-api
spec:
  type: ClusterIP
  selector:
    app: bovipro-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
