apiVersion: v1
kind: Service
metadata:
  name: beeai-ai
  namespace: beeai-prod
  labels:
    app: beeai-ai
spec:
  type: ClusterIP
  selector:
    app: beeai-ai
  ports:
    - name: http
      port: 8001
      targetPort: 8001
