apiVersion: v1
kind: Service
metadata:
  name: traduxai-web
  namespace: traduxai-dev
  labels:
    app: traduxai-web
spec:
  type: ClusterIP
  selector:
    app: traduxai-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
