###############################################################################
# SecretProviderClass — lê secrets do Key Vault kv-bovipro-dev.
# Requer: secrets-store-csi-driver + azure-key-vault-provider no AKS.
###############################################################################
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bovipro-kv-secrets
  namespace: bovipro-dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "fc112ff8-3d3a-46b4-af5c-d2cb864809cf"   # azurekeyvaultsecretsprovider-aks-shared-dev
    clientID: "fc112ff8-3d3a-46b4-af5c-d2cb864809cf"
    keyvaultName: "kv-bovipro-dev"
    objects: |
      array:
        - |
          objectName: bovipro-pg-connection
          objectType: secret
        - |
          objectName: bovipro-jwt-secret
          objectType: secret
    tenantId: "7377a982-cbdf-40d4-af3d-281d65c00164"           # preenchido automaticamente via Managed Identity
  secretObjects:
    - secretName: bovipro-secrets
      type: Opaque
      data:
        - objectName: bovipro-pg-connection
          key: DATABASE_URL
        - objectName: bovipro-jwt-secret
          key: JWT_SECRET
