apiVersion: v1
kind: Service
metadata:
  name: bovipro-web
  namespace: bovipro
  labels:
    app: bovipro-web
spec:
  type: ClusterIP
  selector:
    app: bovipro-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
